
# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "v1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[constraint]]
  branch = "b64_srv"
  name = "github.com/katzenpost/core"

[[constraint]]
  branch = "clockwork.1"
  name = "github.com/katzenpost/authority"

[[override]]
  branch = "voting_release"
  name = "github.com/katzenpost/mailproxy"

[[override]]
  branch = "fix_peercredentials_use"
  name = "github.com/katzenpost/minclient"

[[override]]
  branch = "add_clockwork"
  name = "github.com/katzenpost/server"

# other stuff

[[override]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[override]]
  name = "github.com/abiosoft/ishell"
  version = "2.0.0"

[[override]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[override]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/hpcloud/tail"

[prune]
  go-tests = true
  unused-packages = true
